### ISSUE TITLE
doesn't work 

### ISSUE THREAD

**Issue by rushi3691** [vivekvamsi-VV/Goindex-Folder-Downloader#1]
i gave the username , password and link but doesn't work. I think they have updated the structure

**Comment by vivekvamsi-VV** [comment]
This was implemented for browser https on prompt authentication. But the page on script is now taking login via token based authentication. Working on that too, but cloudflare is supposedly not allowing firing multiple wgets to work seamlessly as before. Will release that script in another repo when ready.
